const timetableData = [
  // Monday
  {
    day: "Monday",
    start: "1:30",
    end: "3:30",
    subject: "EAE 355T",
    faculty: "Ms. Kashika Wadhwa",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Monday",
    start: "3:30",
    end: "5:30",
    subject: "PC 303",
    faculty: "Ms. Richa",
    room: "ECR 601",
    type: "Theory",
  },

  // Tuesday
  {
    day: "Tuesday",
    start: "1:30",
    end: "2:30",
    subject: "EAE 355T",
    faculty: "Ms. Kashika Wadhwa",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Tuesday",
    start: "2:30",
    end: "3:30",
    subject: "PE 333T",
    faculty: "Dr. Ankita Sharma",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Tuesday",
    start: "3:30",
    end: "4:30",
    subject: "PC 303",
    faculty: "Ms. Richa",
    room: "ECR 601",
    type: "Theory",
  },

  // Wednesday
  {
    day: "Wednesday",
    start: "1:30",
    end: "3:30",
    subject: "PE 333T",
    faculty: "Dr. Ankita Sharma",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Wednesday",
    start: "3:30",
    end: "5:30",
    subject: "PC 321",
    faculty: "TBA",
    room: "NBLAB2",
    type: "Lab",
  },

  // Thursday
  {
    day: "Thursday",
    start: "9:00",
    end: "10:00",
    subject: "PC 301",
    faculty: "RS Manisha Sharma",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Thursday",
    start: "10:00",
    end: "11:00",
    subject: "PC 349T",
    faculty: "CF Dr. Reena Tripathi",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Thursday",
    start: "11:00",
    end: "1:00",
    subject: "PC 305",
    faculty: "CF Mr. Harshit Kumar",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Thursday",
    start: "1:30",
    end: "3:30",
    subject: "PE 333P",
    faculty: "CF Dr. Ankita Sharma",
    room: "NBLAB2",
    type: "Practical",
  },
  {
    day: "Thursday",
    start: "3:30",
    end: "5:30",
    subject: "PC 323",
    faculty: "CF Mr. Harshit Kumar",
    room: "NBLAB2",
    type: "Practical",
  },

  // Friday
  {
    day: "Friday",
    start: "9:00",
    end: "10:00",
    subject: "PC 301",
    faculty: "RS Manisha Sharma",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Friday",
    start: "10:00",
    end: "12:00",
    subject: "PC 349T",
    faculty: "CF Dr. Reena Tripathi",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Friday",
    start: "12:00",
    end: "1:00",
    subject: "PC 305",
    faculty: "CF Mr. Harshit Kumar",
    room: "ECR 601",
    type: "Theory",
  },
  {
    day: "Friday",
    start: "1:30",
    end: "3:30",
    subject: "EAE 355P",
    faculty: "TBA",
    room: "NBLAB2",
    type: "Practical",
  },
  {
    day: "Friday",
    start: "3:30",
    end: "5:30",
    subject: "PC 349P",
    faculty: "CF Dr. Reena Tripathi",
    room: "NBLAB2",
    type: "Practical",
  },
];

module.exports = timetableData;
